### ISSUE TITLE
What OPC UA Server Profiles do you support?

### ISSUE THREAD

**Issue by gillerman** [fledge-power/fledge-north-s2opcua#17]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vmo6trl** [comment]
Hello,

The current version supported profile is OPC UA Nano profile with additional support of Subscription services.
Subscription services limitations: no monitoredItems filters or deletion, no subscription transfer.
The plugin uses S2OPC library v1.3.0, you might find more information in the [README file](https://gitlab.com/systerel/S2OPC/-/blob/S2OPC_Toolkit_1.3.0/README.md).

Best regards.
