### ISSUE TITLE
Exceptions, errors and logs management

### ISSUE THREAD

**Issue by vmo6trl** [fledge-power/fledge-north-s2opcua#6]
The plugin shall produce log traces during execution.
The implemented code shall follow the code review checklist. [coding rules](https://github.com/fledge-power/contributing/blob/main/CPPCODINGRULES.md).

**Comment by jchabod** [comment]
S2OPC log features have been routed to FLEDGE logger according to log level.

**Comment by jchabod** [comment]
CPPLINT is applied and a Makefile rule has been added.
