### ISSUE TITLE
Integrate S2OPC library into north plugin code

### ISSUE THREAD

**Issue by vmo6trl** [fledge-power/fledge-north-s2opcua#7]
- Create an empty north plugin
- Compile dependencies of north s2opcua plugin
- Initialize S2OPC library into plugin
- Compile, install and test plugin using Fledge GUI

**Comment by jchabod** [comment]
Updated on 07/09/2022:
Migrate CMake rules to use S2OPC as intended (simple "find_package")

A simple server containing only the namespace 0 is running in FLEDGE (tested basically as a task, not a service)

SHA1: b72a89db2fb009ded1fd7966ba0d41714cd973fe

**Comment by jchabod** [comment]
The branch `north_plugin_dev` contain final development code including corrected features
